<a href="https://colab.research.google.com/github/PranaviBurrareddy/PranaviBurrareddy/blob/main/bmi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy
arr = numpy.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [5]:
a_1d=np.array([1,2,3,4])
a_1d

array([1, 2, 3, 4])

In [6]:
type(a_1d)

numpy.ndarray

In [10]:
#to check data type
type(a_1d)

numpy.ndarray

In [11]:
a_1d.dtype

dtype('int64')

In [12]:
a_1d.size

4

In [13]:
a_1d.ndim

1

In [14]:
a_1d.shape

(4,)

In [17]:
#3d array
a_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
a_3d=np.array([[1,2,4,3],[5,6,7,8],[3,4,5,6]])
a_3d

array([[1, 2, 4, 3],
       [5, 6, 7, 8],
       [3, 4, 5, 6]])

In [20]:
a_2d+a_3d

array([[ 2,  4,  7,  7],
       [10, 12, 14, 16],
       [12, 14, 16, 18]])

In [21]:
a_4d=np.array([1,2,3,4])
a_4d

array([1, 2, 3, 4])

In [22]:
type(a_2d)

numpy.ndarray

In [23]:
import numpy as np
import matplotlib.pyplot as plt

In [24]:
np.sin(100)

-0.5063656411097588

In [25]:
np.cos(100)

0.8623188722876839

In [26]:
np.tan(100)

-0.5872139151569291

In [27]:
a_2d=np.zeros((4,3),dtype=int)
a_2d

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
import pandas as pd


In [32]:
emt_df = pd.DataFrame( )
print(emt_df)


Empty DataFrame
Columns: []
Index: []


In [33]:
height=float(input("enter your height in centimeters: "))
weight=float(input("enter your weight in kg: "))
height = height/100
BMI = weight/(height*height)
print("your body mass index is: ",BMI)

enter your height in centimeters: 162
enter your weight in kg: 65
your body mass index is:  24.76756591982929


In [35]:
if(BMI>0):
  if(BMI<=16):
    print("you are severly under weight")
  elif(BMI<=18.5):
    print("you are under weight")
  elif(BMI<=25):
    print("you are over weight")
  else:print("you are severely over weight")
else:("enter valid details")

you are over weight
